on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run lint
      - run: npm run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Run test pipline
        uses: sophos/factory-run-pipeline@master
        with:
          project_id: 61cca573d42b9b46428365c8
          job_id: 61ccb67ad42b9b7cc08365d4
          api_token: '${{ secrets.FACTORY_API_TOKEN }}'
          api_url: 'https://api.dev.factory.sophos.com/v1'
